<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Doctor Video Personalisation | Meyer Vitabiotics</title>@include('partials.assets')</head>
<body><main class="page-shell"><section class="form-card" aria-labelledby="page-title">
<header class="brand-header"><img src="{{ asset('assets/meyer-vitabiotics.jpg') }}" alt="Meyer Vitabiotics" class="brand-logo"><span class="header-rule"></span><p>Doctor video personalisation</p></header>
@if($errors->any())<div class="alert alert-error" role="alert"><strong>Please check the details below.</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
@if($completedUser)
<div class="result-panel" id="result"><div class="success-icon">✓</div><div><h2>Your personalised video is ready</h2><p>{{ $completedUser->prefix }} {{ $completedUser->name }} · {{ $completedUser->city }}</p></div><video controls playsinline preload="metadata" src="{{ $completedUser->video_url }}"></video><a class="download-button" href="{{ route('video.download',[$completedUser,$completedUser->download_token]) }}">Download video</a><a class="new-link" href="{{ route('video.form') }}">Create another video</a></div>
@else
<div class="intro"><span class="eyebrow">Personalised in moments</span><h1 id="page-title">Create a doctor video</h1><p>Enter the doctor's details and add a clear photograph. The personalised introduction will appear from 28 seconds.</p></div>
<form action="{{ route('video.generate') }}" method="POST" enctype="multipart/form-data" id="video-form" novalidate>@csrf
<div class="field-grid">
<label class="field full"><span>Employee code</span><input type="text" name="employee_code" value="{{ old('employee_code') }}" maxlength="30" pattern="[A-Za-z0-9]+" placeholder="e.g. MV1024" required autocomplete="off"><small class="field-error" data-error-for="employee_code"></small></label>
<label class="field prefix-field"><span>Prefix</span><select name="prefix" required><option value="" disabled {{ old('prefix')?'':'selected' }}>Select</option>@foreach(['Dr.','Prof.','Mr.','Ms.','Mrs.'] as $prefix)<option value="{{ $prefix }}" @selected(old('prefix')===$prefix)>{{ $prefix }}</option>@endforeach</select><small class="field-error" data-error-for="prefix"></small></label>
<label class="field name-field"><span>Doctor name</span><input type="text" name="doctor_name" value="{{ old('doctor_name') }}" maxlength="80" placeholder="Full name" required autocomplete="name"><small class="field-error" data-error-for="doctor_name"></small></label>
<label class="field full"><span>City <small>(optional)</small></span><input type="text" name="city" value="{{ old('city') }}" maxlength="80" placeholder="Enter city" autocomplete="address-level2"><small class="field-error" data-error-for="city"></small></label>
</div>
<div class="photo-section"><div class="section-heading"><div><span>Doctor photo</span><small>JPG or PNG · max 8 MB</small></div><span class="step-pill">Circular crop</span></div><div class="photo-workspace"><button type="button" class="photo-picker" id="photo-picker"><span class="photo-preview" id="photo-preview"><svg viewBox="0 0 24 24"><path d="M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm7 8a7 7 0 0 0-14 0h14Z"/></svg></span><span><strong>Choose a photo</strong><small>Click to browse and crop</small></span></button><input type="file" id="photo-input" accept="image/jpeg,image/png,image/webp" hidden><input type="file" name="photo" id="cropped-photo" hidden required></div><p class="photo-error" id="photo-error" role="alert"></p></div>
<button class="submit-button" type="submit" id="submit-button"><span class="button-label">Generate personalised video</span><span class="button-loader"></span><svg viewBox="0 0 24 24"><path d="m9 18 6-6-6-6"/></svg></button><p class="processing-note">Video processing and secure upload may take up to a minute. Please keep this page open.</p></form>
<div class="crop-modal" id="crop-modal" hidden role="dialog" aria-modal="true" aria-labelledby="crop-title"><div class="crop-dialog"><div class="crop-modal-header"><div><span class="eyebrow">Doctor photo</span><h2 id="crop-title">Crop your photo</h2></div><button type="button" class="modal-close" id="crop-cancel" aria-label="Close crop popup">×</button></div><div class="crop-stage"><canvas id="crop-canvas" width="360" height="360"></canvas></div><div class="crop-controls"><span>Zoom</span><button type="button" id="zoom-out" aria-label="Zoom out">−</button><input type="range" id="zoom" min="1" max="4" value="1" step=".01"><button type="button" id="zoom-in" aria-label="Zoom in">+</button><strong id="zoom-value">1.0×</strong></div><p class="crop-hint">Drag the photo to reposition it inside the circle.</p><div class="crop-actions"><button type="button" class="secondary-button" id="crop-back">Cancel</button><button type="button" class="submit-button" id="crop-apply">Use this crop</button></div></div></div>
@endif</section><p class="footer-note">For authorised Meyer Vitabiotics employees only</p></main></body></html>
