<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Submissions</title>@include('partials.assets')</head><body class="admin-body">@include('admin.sidebar')
<main class="dashboard-main"><header class="dashboard-topbar"><div><span>Submissions</span><small>Search and manage doctor videos</small></div></header><div class="dashboard-content"><div class="dashboard-title"><div><span class="eyebrow">Listing</span><h1>Doctor video submissions</h1></div></div>
<section class="table-card"><div class="listing-toolbar"><form method="GET" action="{{ route('admin.submissions') }}" class="search-form"><input type="search" name="search" value="{{ $search }}" placeholder="Search doctor, employee code, city or status"><button type="submit">Search</button>@if($search)<a href="{{ route('admin.submissions') }}">Clear</a>@endif</form><a class="export-button" href="{{ route('admin.export') }}">Export Excel</a></div>
<div class="table-wrap"><table><thead><tr><th>Doctor</th><th>Employee code</th><th>City</th><th>Status</th><th>Submitted</th><th>Photo</th><th>Video</th></tr></thead><tbody>
@forelse($submissions as $submission)<tr>
<td><div class="doctor-cell"><div><strong>{{ $submission->prefix }} {{ $submission->name }}</strong><small>Record #{{ $submission->id }}</small></div></div></td>
<td><span class="employee-code">{{ $submission->employee_code }}</span></td><td class="city-cell">{{ $submission->city ?: '—' }}</td><td><span class="status status-{{ $submission->video_status }}">{{ ucfirst($submission->video_status) }}</span></td><td>{{ $submission->created_at->format('d M Y') }}<small class="table-time">{{ $submission->created_at->format('h:i A') }}</small></td>
<td>@if($submission->photo_url)<a href="{{ $submission->photo_url }}" target="_blank" class="photo-column-preview"><img src="{{ $submission->photo_url }}" alt="{{ $submission->name }} photo"><span>View</span></a>@else<span class="muted">—</span>@endif</td>
<td>@if($submission->video_status==='completed')<a class="video-column-link" href="{{ route('admin.download',$submission) }}">Download</a>@else<span class="muted">—</span>@endif</td>
</tr>@empty<tr><td colspan="7" class="empty-state">No matching submissions.</td></tr>@endforelse
</tbody></table></div>
@if($submissions->hasPages())<div class="admin-pagination"><div>Showing {{ $submissions->firstItem() }}–{{ $submissions->lastItem() }} of {{ $submissions->total() }}</div><nav>@if($submissions->onFirstPage())<span class="disabled">Previous</span>@else<a href="{{ $submissions->previousPageUrl() }}">Previous</a>@endif @foreach($submissions->getUrlRange(max(1,$submissions->currentPage()-2),min($submissions->lastPage(),$submissions->currentPage()+2)) as $page=>$url)<a href="{{ $url }}" class="{{ $page===$submissions->currentPage()?'current':'' }}">{{ $page }}</a>@endforeach @if($submissions->hasMorePages())<a href="{{ $submissions->nextPageUrl() }}">Next</a>@else<span class="disabled">Next</span>@endif</nav></div>@endif
</section></div></main></body></html>
